// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelocityBoard.Infrastructure.Data;

#nullable disable

namespace VelocityBoard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VelocityBoard.Core.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5010),
                            Name = "Website Redesign"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5023),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 3,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5025),
                            Name = "Marketing Campaign"
                        });
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToUserId = 2,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5053),
                            DueDate = new DateTime(2025, 12, 22, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5045),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Design Homepage"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 1,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5056),
                            DueDate = new DateTime(2025, 12, 20, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5054),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Setup Database"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 3,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5058),
                            DueDate = new DateTime(2025, 12, 27, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5057),
                            Priority = 1,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Develop Login API"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 3,
                            CreatedDate = new DateTime(2025, 12, 17, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5061),
                            DueDate = new DateTime(2025, 12, 24, 20, 37, 42, 785, DateTimeKind.Local).AddTicks(5059),
                            Priority = 0,
                            ProjectId = 3,
                            Status = 0,
                            Title = "Create Ad Copy"
                        });
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@velocityboard.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "$2y$10$ievgpt4SzPDI30dKyajspuWyeW2uQ6KvCsQZIa3koo1OT6g1Zm006",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcflpP3OvI0Cz",
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcflpP3OvI0Cz",
                            UserName = "jane.smith"
                        });
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.Project", b =>
                {
                    b.HasOne("VelocityBoard.Core.Models.User", "CreatedByUser")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.TaskItem", b =>
                {
                    b.HasOne("VelocityBoard.Core.Models.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VelocityBoard.Core.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("VelocityBoard.Core.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
